from sqlalchemy import text
from sqlalchemy.exc import ProgrammingError

def _rodar_etl_model(conn):
    """
    Popula/atualiza o schema lacreisaude_model a partir da staging_02.
    - Usa chaves naturais com UNIQUE INDEX para garantir idempotência.
    - Todos os INSERTs usam ON CONFLICT (<colunas>) ... (não por nome de constraint).
    """

    # -------------------------------------------------------------------------
    # 0) Schema
    # -------------------------------------------------------------------------
    conn.execute(text("CREATE SCHEMA IF NOT EXISTS lacreisaude_model;"))

    # -------------------------------------------------------------------------
    # 1) DIM DATE
    # -------------------------------------------------------------------------
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS lacreisaude_model.dim_lacreisaude_date
        (
            date_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            calendar_date DATE NOT NULL UNIQUE,
            day           INTEGER NOT NULL,
            month         INTEGER NOT NULL,
            year          INTEGER NOT NULL,
            week          INTEGER NOT NULL,
            quarter       INTEGER NOT NULL
        );
    """))

    conn.execute(text("""
        WITH all_dates AS (
            SELECT DISTINCT (appointment_date::date) AS d
            FROM lacreisaude_staging_02.lacreiid_appointment
            WHERE appointment_date IS NOT NULL
            UNION
            SELECT DISTINCT (created_at::date) AS d
            FROM lacreisaude_staging_02.lacreiid_appointment
            WHERE created_at IS NOT NULL
        )
        INSERT INTO lacreisaude_model.dim_lacreisaude_date
            (calendar_date, day, month, year, week, quarter)
        SELECT
            d                                           AS calendar_date,
            EXTRACT(DAY FROM d)::int                    AS day,
            EXTRACT(MONTH FROM d)::int                  AS month,
            EXTRACT(YEAR FROM d)::int                   AS year,
            EXTRACT(WEEK FROM d)::int                   AS week,
            EXTRACT(QUARTER FROM d)::int                AS quarter
        FROM all_dates
        ON CONFLICT (calendar_date) DO NOTHING;
    """))

    # -------------------------------------------------------------------------
    # 2) DIM CANCELLATION  (chave natural: created_at, reason)
    # -------------------------------------------------------------------------
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS lacreisaude_model.dim_lacreisaude_cancellation
        (
            cancellation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at      TIMESTAMP WITHOUT TIME ZONE,
            reason          VARCHAR
        );
        CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_cancel_created_reason
            ON lacreisaude_model.dim_lacreisaude_cancellation (created_at, reason);
    """))

    conn.execute(text("""
        INSERT INTO lacreisaude_model.dim_lacreisaude_cancellation (created_at, reason)
        SELECT DISTINCT c.created_at, c.reason
        FROM lacreisaude_staging_02.lacreiid_cancellation c
        WHERE c.created_at IS NOT NULL OR c.reason IS NOT NULL
        ON CONFLICT (created_at, reason) DO NOTHING;
    """))

    # -------------------------------------------------------------------------
    # 3) DIM REPORT  (chave natural: created_at, feedback, evaluation)
    # -------------------------------------------------------------------------
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS lacreisaude_model.dim_lacreisaude_report
        (
            report_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at  TIMESTAMP WITHOUT TIME ZONE,
            feedback    VARCHAR,
            evaluation  INTEGER
        );
        CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_report_created_feedback_eval
            ON lacreisaude_model.dim_lacreisaude_report (created_at, feedback, evaluation);
    """))

    conn.execute(text("""
        INSERT INTO lacreisaude_model.dim_lacreisaude_report (created_at, feedback, evaluation)
        SELECT DISTINCT r.created_at, r.feedback, r.eval
        FROM lacreisaude_staging_02.lacreiid_report r
        WHERE r.created_at IS NOT NULL OR r.feedback IS NOT NULL OR r.eval IS NOT NULL
        ON CONFLICT (created_at, feedback, evaluation) DO NOTHING;
    """))

    # -------------------------------------------------------------------------
    # 4) DIM CLINIC  (chave natural: name, city, state)
    # -------------------------------------------------------------------------
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS lacreisaude_model.dim_lacreisaude_clinic
        (
            clinic_id                               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at                              TIMESTAMP WITHOUT TIME ZONE,
            is_presential_clinic                    BOOLEAN,
            is_online_clinic                        BOOLEAN,
            name                                    VARCHAR,
            zip_code                                VARCHAR,
            city                                    VARCHAR,
            consult_price                           NUMERIC(10,2),
            duration_minutes                        INTEGER,
            accepts_insurance_providers             BOOLEAN,
            provides_accessibility_standards        BOOLEAN,
            online_clinic_consult_price             NUMERIC(10,2),
            online_clinic_duration_minutes          INTEGER,
            online_clinic_accepts_insurance_providers BOOLEAN,
            state                                   VARCHAR
        );
        CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_clinic_name_city_state
            ON lacreisaude_model.dim_lacreisaude_clinic (name, city, state);
    """))

    conn.execute(text("""
        INSERT INTO lacreisaude_model.dim_lacreisaude_clinic
        (
            created_at, is_presential_clinic, is_online_clinic, name, zip_code, city,
            consult_price, duration_minutes, accepts_insurance_providers,
            provides_accessibility_standards, online_clinic_consult_price,
            online_clinic_duration_minutes, online_clinic_accepts_insurance_providers, state
        )
        SELECT DISTINCT
            c.created_at, c.is_presential_clinic, c.is_online_clinic, c.name, c.zip_code, c.city,
            c.consult_price, c.duration_minutes, c.accepts_insurance_providers,
            c.provides_accessibility_standards, c.online_clinic_consult_price,
            c.online_clinic_duration_minutes, c.online_clinic_accepts_insurance_providers,
            (c.state_id::text) AS state
        FROM lacreisaude_staging_02.lacreisaude_clinic c
        WHERE c.name IS NOT NULL
        ON CONFLICT (name, city, state) DO UPDATE SET
            created_at                       = EXCLUDED.created_at,
            is_presential_clinic             = EXCLUDED.is_presential_clinic,
            is_online_clinic                 = EXCLUDED.is_online_clinic,
            zip_code                         = EXCLUDED.zip_code,
            consult_price                    = EXCLUDED.consult_price,
            duration_minutes                 = EXCLUDED.duration_minutes,
            accepts_insurance_providers      = EXCLUDED.accepts_insurance_providers,
            provides_accessibility_standards = EXCLUDED.provides_accessibility_standards,
            online_clinic_consult_price      = EXCLUDED.online_clinic_consult_price,
            online_clinic_duration_minutes   = EXCLUDED.online_clinic_duration_minutes,
            online_clinic_accepts_insurance_providers = EXCLUDED.online_clinic_accepts_insurance_providers;
    """))

    # -------------------------------------------------------------------------
    # 5) DIM PROFESSIONAL  (chave natural: full_name, state)
    # -------------------------------------------------------------------------
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS lacreisaude_model.dim_lacreisaude_professional
        (
            professional_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at       TIMESTAMP WITHOUT TIME ZONE,
            full_name        VARCHAR,
            profile_status   VARCHAR,
            active           BOOLEAN,
            published        BOOLEAN,
            specialty        VARCHAR,
            ethnic_group     VARCHAR,
            gender_identity  VARCHAR,
            pronoun          VARCHAR,
            sexual_orientation VARCHAR,
            profile_type     VARCHAR,
            disability_type  TEXT[],
            state            VARCHAR
        );
        CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_prof_fullname_state
            ON lacreisaude_model.dim_lacreisaude_professional (full_name, state);
    """))

    conn.execute(text("""
        WITH disab AS (
            SELECT pdt.professional_id,
                   ARRAY_REMOVE(ARRAY_AGG(pdt.disabilitytype_id::text), NULL) AS disab_arr
            FROM lacreisaude_staging_02.lacreisaude_professional_disability_types pdt
            GROUP BY pdt.professional_id
        )
        INSERT INTO lacreisaude_model.dim_lacreisaude_professional
        (
            created_at, full_name, profile_status, active, published, specialty,
            ethnic_group, gender_identity, pronoun, sexual_orientation, profile_type,
            disability_type, state
        )
        SELECT DISTINCT
            p.created_at, p.full_name, p.profile_status, p.active, p.published, p.specialty,
            p.ethnic_group::text, p.gender_identity::text, p.pronoun::text, p.sexual_orientation::text,
            NULL::text AS profile_type,  -- não temos profile_type direto no professional
            COALESCE(d.disab_arr, ARRAY[]::text[]) AS disability_type,
            (p.state_id::text) AS state
        FROM lacreisaude_staging_02.lacreisaude_professional p
        LEFT JOIN disab d ON d.professional_id = p.professional_id::varchar
        WHERE p.full_name IS NOT NULL
        ON CONFLICT (full_name, state) DO UPDATE SET
            created_at        = EXCLUDED.created_at,
            profile_status    = EXCLUDED.profile_status,
            active            = EXCLUDED.active,
            published         = EXCLUDED.published,
            specialty         = EXCLUDED.specialty,
            ethnic_group      = EXCLUDED.ethnic_group,
            gender_identity   = EXCLUDED.gender_identity,
            pronoun           = EXCLUDED.pronoun,
            sexual_orientation= EXCLUDED.sexual_orientation,
            disability_type   = EXCLUDED.disability_type;
    """))

    # -------------------------------------------------------------------------
    # 6) DIM PATIENT  (chave natural: first_name, last_name, birth_date)
    # -------------------------------------------------------------------------
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS lacreisaude_model.dim_lacreisaude_patient
        (
            patient_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at      TIMESTAMP WITHOUT TIME ZONE,
            first_name      VARCHAR,
            last_name       VARCHAR,
            birth_date      TIMESTAMP WITHOUT TIME ZONE,
            is_active       BOOLEAN,
            profile_type    VARCHAR,
            ethnic_group    VARCHAR,
            gender_identity VARCHAR,
            pronoun         VARCHAR,
            sexual_orientation VARCHAR,
            disability_type TEXT[]
        );
        CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_patient_name_birth
            ON lacreisaude_model.dim_lacreisaude_patient (first_name, last_name, birth_date);
    """))

    conn.execute(text("""
        WITH prof_disab AS (
            SELECT pdt.profile_id,
                   ARRAY_REMOVE(ARRAY_AGG(pdt.disabilitytype_id::text), NULL) AS disab_arr
            FROM lacreisaude_staging_02.lacreiid_profile_disability_types pdt
            GROUP BY pdt.profile_id
        ),
        base AS (
            SELECT
                u.created_at AS created_at,
                u.first_name,
                u.last_name,
                u.birth_date,
                u.is_active,
                pd.profile_type,
                pr.ethnic_group::text        AS ethnic_group,
                pr.gender_identity::text     AS gender_identity,
                pr.pronoun::text             AS pronoun,
                pr.sexual_orientation::text  AS sexual_orientation,
                COALESCE(d.disab_arr, ARRAY[]::text[]) AS disability_type
            FROM lacreisaude_staging_02.lacreiid_user u
            LEFT JOIN lacreisaude_staging_02.lacreiid_profile pr
                   ON pr.user_id = u.user_id
            LEFT JOIN prof_disab d
                   ON d.profile_id = pr.profile_id
            LEFT JOIN lacreisaude_staging_02.lacrei_privacydocument pd
                   ON pd.id = u.privacy_document_id
        )
        INSERT INTO lacreisaude_model.dim_lacreisaude_patient
        (
            created_at, first_name, last_name, birth_date, is_active, profile_type,
            ethnic_group, gender_identity, pronoun, sexual_orientation, disability_type
        )
        SELECT DISTINCT
            created_at, first_name, last_name, birth_date, is_active, profile_type,
            ethnic_group, gender_identity, pronoun, sexual_orientation, disability_type
        FROM base
        WHERE first_name IS NOT NULL OR last_name IS NOT NULL OR birth_date IS NOT NULL
        ON CONFLICT (first_name, last_name, birth_date) DO UPDATE SET
            created_at       = EXCLUDED.created_at,
            is_active        = EXCLUDED.is_active,
            profile_type     = EXCLUDED.profile_type,
            ethnic_group     = EXCLUDED.ethnic_group,
            gender_identity  = EXCLUDED.gender_identity,
            pronoun          = EXCLUDED.pronoun,
            sexual_orientation = EXCLUDED.sexual_orientation,
            disability_type  = EXCLUDED.disability_type;
    """))

    # -------------------------------------------------------------------------
    # 7) FACT APPOINTMENTS
    # -------------------------------------------------------------------------
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS lacreisaude_model.fact_lacreisaude_appointments
        (
            id_fact_appointment INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_date_id     INTEGER REFERENCES lacreisaude_model.dim_lacreisaude_date(date_id),
            status              VARCHAR,
            type                VARCHAR,
            date_id             INTEGER NOT NULL REFERENCES lacreisaude_model.dim_lacreisaude_date(date_id),
            waiting_time        NUMERIC,
            professional_id     INTEGER REFERENCES lacreisaude_model.dim_lacreisaude_professional(professional_id),
            patient_id          INTEGER REFERENCES lacreisaude_model.dim_lacreisaude_patient(patient_id),
            clinic_id           INTEGER REFERENCES lacreisaude_model.dim_lacreisaude_clinic(clinic_id),
            report_id           INTEGER REFERENCES lacreisaude_model.dim_lacreisaude_report(report_id),
            cancellation_id     INTEGER REFERENCES lacreisaude_model.dim_lacreisaude_cancellation(cancellation_id)
        );
        CREATE INDEX IF NOT EXISTS idx_fact_date_id          ON lacreisaude_model.fact_lacreisaude_appointments(date_id);
        CREATE INDEX IF NOT EXISTS idx_fact_created_date_id  ON lacreisaude_model.fact_lacreisaude_appointments(created_date_id);
        CREATE INDEX IF NOT EXISTS idx_fact_professional_id  ON lacreisaude_model.fact_lacreisaude_appointments(professional_id);
        CREATE INDEX IF NOT EXISTS idx_fact_patient_id       ON lacreisaude_model.fact_lacreisaude_appointments(patient_id);
        CREATE INDEX IF NOT EXISTS idx_fact_report_id        ON lacreisaude_model.fact_lacreisaude_appointments(report_id);
        CREATE INDEX IF NOT EXISTS idx_fact_cancellation_id  ON lacreisaude_model.fact_lacreisaude_appointments(cancellation_id);
        CREATE INDEX IF NOT EXISTS idx_fact_clinic_id        ON lacreisaude_model.fact_lacreisaude_appointments(clinic_id);
    """))

    conn.execute(text("""
        WITH ap AS (
            SELECT
                a.id,
                a.status,
                a.type,
                a.appointment_date::date  AS appt_d,
                a.created_at::date        AS created_d,
                a.professional_id,
                a.user_id
            FROM lacreisaude_staging_02.lacreiid_appointment a
        ),
        d_appt AS (
            SELECT d.calendar_date, d.date_id
            FROM lacreisaude_model.dim_lacreisaude_date d
        ),
        d_created AS (
            SELECT d.calendar_date, d.date_id
            FROM lacreisaude_model.dim_lacreisaude_date d
        ),
        prof_src AS (
            SELECT p.professional_id::varchar AS src_prof_id, p.full_name, (p.state_id::text) AS state
            FROM lacreisaude_staging_02.lacreisaude_professional p
        ),
        d_prof AS (
            SELECT dp.professional_id, dp.full_name, dp.state
            FROM lacreisaude_model.dim_lacreisaude_professional dp
        ),
        user_src AS (
            SELECT u.user_id, u.first_name, u.last_name, u.birth_date
            FROM lacreisaude_staging_02.lacreiid_user u
        ),
        d_pat AS (
            SELECT dp.patient_id, dp.first_name, dp.last_name, dp.birth_date
            FROM lacreisaude_model.dim_lacreisaude_patient dp
        ),
        rep_src AS (
            SELECT r.appointment_id, r.created_at, r.feedback, r.eval
            FROM lacreisaude_staging_02.lacreiid_report r
        ),
        d_rep AS (
            SELECT dr.report_id, dr.created_at, dr.feedback, dr.evaluation
            FROM lacreisaude_model.dim_lacreisaude_report dr
        ),
        canc_src AS (
            SELECT c.appointment_id, c.created_at, c.reason
            FROM lacreisaude_staging_02.lacreiid_cancellation c
        ),
        d_canc AS (
            SELECT dc.cancellation_id, dc.created_at, dc.reason
            FROM lacreisaude_model.dim_lacreisaude_cancellation dc
        ),
        joined AS (
            SELECT
                ap.id AS src_appointment_id,
                ap.status, ap.type,

                dap.date_id    AS date_id,
                dcr.date_id    AS created_date_id,

                -- PROFESSIONAL
                dp.professional_id AS professional_id,

                -- PATIENT
                dpa.patient_id AS patient_id,

                -- REPORT
                dr.report_id   AS report_id,

                -- CANCELLATION
                dc.cancellation_id AS cancellation_id

            FROM ap
            LEFT JOIN d_appt   dap ON dap.calendar_date = ap.appt_d
            LEFT JOIN d_created dcr ON dcr.calendar_date = ap.created_d

            LEFT JOIN prof_src ps  ON ps.src_prof_id::integer = ap.professional_id
            LEFT JOIN d_prof   dp  ON dp.full_name = ps.full_name AND dp.state = ps.state

            LEFT JOIN user_src us  ON us.user_id = ap.user_id::varchar
            LEFT JOIN d_pat   dpa  ON dpa.first_name = us.first_name
                                   AND dpa.last_name  = us.last_name
                                   AND ((dpa.birth_date IS NULL AND us.birth_date IS NULL)
                                        OR dpa.birth_date = us.birth_date)

            LEFT JOIN rep_src rs   ON rs.appointment_id = ap.id
            LEFT JOIN d_rep   dr   ON dr.created_at = rs.created_at
                                   AND COALESCE(dr.feedback, '') = COALESCE(rs.feedback, '')
                                   AND COALESCE(dr.evaluation, -2147483648) = COALESCE(rs.eval, -2147483648)

            LEFT JOIN canc_src cs  ON cs.appointment_id = ap.id::varchar
            LEFT JOIN d_canc  dc   ON dc.created_at = cs.created_at
                                   AND COALESCE(dc.reason, '') = COALESCE(cs.reason, '')
        )
        INSERT INTO lacreisaude_model.fact_lacreisaude_appointments
        (
            created_date_id, status, type, date_id, waiting_time,
            professional_id, patient_id, clinic_id, report_id, cancellation_id
        )
        SELECT DISTINCT
            j.created_date_id, j.status, j.type, j.date_id, NULL::numeric,
            j.professional_id, j.patient_id, NULL::integer, j.report_id, j.cancellation_id
        FROM joined j
        WHERE NOT EXISTS (
            SELECT 1
            FROM lacreisaude_model.fact_lacreisaude_appointments f
            WHERE f.date_id = j.date_id
              AND COALESCE(f.created_date_id, -1) = COALESCE(j.created_date_id, -1)
              AND COALESCE(f.professional_id, -1) = COALESCE(j.professional_id, -1)
              AND COALESCE(f.patient_id, -1) = COALESCE(j.patient_id, -1)
              AND COALESCE(f.report_id, -1) = COALESCE(j.report_id, -1)
              AND COALESCE(f.cancellation_id, -1) = COALESCE(j.cancellation_id, -1)
              AND COALESCE(f.status, '') = COALESCE(j.status, '')
              AND COALESCE(f.type, '')   = COALESCE(j.type, '')
        );
    """))

    return {"ok": True, "msg": "ETL do modelo concluído (dimensões e fato atualizados)."}