from sqlalchemy import text
from sqlalchemy.exc import ProgrammingError

def _rodar_etl_model(conn):
    """
    Popula/atualiza o schema lacreisaude_model a partir da staging_02.
    - Usa chaves naturais com UNIQUE INDEX para garantir idempotência.
    - Todos os INSERTs usam ON CONFLICT (<colunas>) ... (não por nome de constraint).
    """

    # -------------------------------------------------------------------------
    # 0) Schema
    # -------------------------------------------------------------------------
    conn.execute(text("CREATE SCHEMA IF NOT EXISTS lacreisaude_model;"))

    # -------------------------------------------------------------------------
    # 1) DIM DATE
    # -------------------------------------------------------------------------
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS lacreisaude_model.dim_lacreisaude_date
        (
            date_id       INTEGER PRIMARY KEY, -- datakey no formato YYYYMMDD
            calendar_date DATE NOT NULL UNIQUE,
            day           INTEGER NOT NULL,
            month         INTEGER NOT NULL,
            year          INTEGER NOT NULL,
            week          INTEGER NOT NULL,
            quarter       INTEGER NOT NULL
        );
    """))

    # Popula dim_lacreisaude_date incrementalmente.
    # Determina min/max das datas da staging_02.lacreiid_appointment, encontra a maior data atual na dim e 
    # gera apenas as datas faltantes usando generate_series  
    conn.execute(text("""
        WITH bounds AS (
            SELECT
                (SELECT MIN(appointment_date)::date FROM lacreisaude_staging_02.lacreiid_appointment WHERE appointment_date IS NOT NULL) AS min_appt,
                (SELECT MIN(created_at)::date FROM lacreisaude_staging_02.lacreiid_appointment WHERE created_at IS NOT NULL) AS min_created,
                (SELECT MAX(appointment_date)::date FROM lacreisaude_staging_02.lacreiid_appointment WHERE appointment_date IS NOT NULL) AS max_appt,
                (SELECT MAX(created_at)::date FROM lacreisaude_staging_02.lacreiid_appointment WHERE created_at IS NOT NULL) AS max_created
        ),
        range AS (
            SELECT
                LEAST(min_appt, min_created)::date AS min_date,
                GREATEST(max_appt, max_created)::date AS max_date
            FROM bounds
        ),
        dim_max AS (
            SELECT COALESCE(MAX(calendar_date), (SELECT min_date FROM range) - INTERVAL '1 day')::date AS max_calendar_date
            FROM lacreisaude_model.dim_lacreisaude_date
        ),
        to_generate AS (
            SELECT generate_series( (dim_max.max_calendar_date + INTERVAL '1 day')::date,
                                    (SELECT max_date FROM range),
                                    INTERVAL '1 day')::date AS d
            FROM dim_max
            WHERE (SELECT max_date FROM range) IS NOT NULL
              AND (dim_max.max_calendar_date + INTERVAL '1 day')::date <= (SELECT max_date FROM range)
        )
        INSERT INTO lacreisaude_model.dim_lacreisaude_date (date_id, calendar_date, day, month, year, week, quarter)
        SELECT
            (EXTRACT(YEAR FROM d)::int * 10000 + EXTRACT(MONTH FROM d)::int * 100 + EXTRACT(DAY FROM d)::int) AS date_id,
            d AS calendar_date,
            EXTRACT(DAY FROM d)::int    AS day,
            EXTRACT(MONTH FROM d)::int  AS month,
            EXTRACT(YEAR FROM d)::int   AS year,
            EXTRACT(WEEK FROM d)::int   AS week,
            EXTRACT(QUARTER FROM d)::int AS quarter
        FROM to_generate
        ON CONFLICT (calendar_date) DO NOTHING;
    """))

    # -------------------------------------------------------------------------
    # 2) DIM CANCELLATION  (chave natural: created_at, reason)
    # -------------------------------------------------------------------------
    # conn.execute(text("""
    #     CREATE TABLE IF NOT EXISTS lacreisaude_model.dim_lacreisaude_cancellation
    #     (
    #         cancellation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    #         created_at      TIMESTAMP WITHOUT TIME ZONE,
    #         reason          VARCHAR
    #     );
    #     CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_cancel_created_reason
    #         ON lacreisaude_model.dim_lacreisaude_cancellation (created_at, reason);
    # """))

    # conn.execute(text("""
    #     INSERT INTO lacreisaude_model.dim_lacreisaude_cancellation (created_at, reason)
    #     SELECT DISTINCT c.created_at, c.reason
    #     FROM lacreisaude_staging_02.lacreiid_cancellation c
    #     WHERE c.created_at IS NOT NULL OR c.reason IS NOT NULL
    #     ON CONFLICT (created_at, reason) DO NOTHING;
    # """))

    # -------------------------------------------------------------------------
    # 3) DIM REPORT  (chave natural: created_at, feedback, evaluation)
    # -------------------------------------------------------------------------
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS lacreisaude_model.dim_lacreisaude_report
        (
            report_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at  TIMESTAMP WITHOUT TIME ZONE,
            feedback    VARCHAR,
            evaluation  INTEGER
        );
        CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_report_created_feedback_eval
            ON lacreisaude_model.dim_lacreisaude_report (created_at, feedback, evaluation);
    """))

    conn.execute(text("""
        INSERT INTO lacreisaude_model.dim_lacreisaude_report (created_at, feedback, evaluation)
        SELECT DISTINCT r.created_at, r.feedback, r.eval
        FROM lacreisaude_staging_02.lacreiid_report r
        WHERE r.created_at IS NOT NULL OR r.feedback IS NOT NULL OR r.eval IS NOT NULL
        ON CONFLICT (created_at, feedback, evaluation) DO NOTHING;
    """))

    # -------------------------------------------------------------------------
    # 4) DIM CLINIC  (chave natural: name, city, state)
    # -------------------------------------------------------------------------
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS lacreisaude_model.dim_lacreisaude_clinic
        (
            clinic_id                               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at                              TIMESTAMP WITHOUT TIME ZONE,
            is_presential_clinic                    BOOLEAN,
            is_online_clinic                        BOOLEAN,
            name                                    VARCHAR,
            zip_code                                VARCHAR,
            city                                    VARCHAR,
            consult_price                           NUMERIC(10,2),
            duration_minutes                        INTEGER,
            accepts_insurance_providers             BOOLEAN,
            provides_accessibility_standards        BOOLEAN,
            online_clinic_consult_price             NUMERIC(10,2),
            online_clinic_duration_minutes          INTEGER,
            online_clinic_accepts_insurance_providers BOOLEAN,
            state                                   VARCHAR
        );
        CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_clinic_name_city_state
            ON lacreisaude_model.dim_lacreisaude_clinic (name, city, state);
    """))

    conn.execute(text("""
        INSERT INTO lacreisaude_model.dim_lacreisaude_clinic
        (
            created_at, is_presential_clinic, is_online_clinic, name, zip_code, city,
            consult_price, duration_minutes, accepts_insurance_providers,
            provides_accessibility_standards, online_clinic_consult_price,
            online_clinic_duration_minutes, online_clinic_accepts_insurance_providers, state
        )
        SELECT DISTINCT
            c.created_at, c.is_presential_clinic, c.is_online_clinic, c.name, c.zip_code, c.city,
            c.consult_price, c.duration_minutes, c.accepts_insurance_providers,
            c.provides_accessibility_standards, c.online_clinic_consult_price,
            c.online_clinic_duration_minutes, c.online_clinic_accepts_insurance_providers,
            COALESCE(s.name, c.state_id::text) AS state
            FROM lacreisaude_staging_02.lacreisaude_clinic c
            LEFT JOIN lacreisaude_staging_02.address_state s
            ON s.id = c.state_id
        WHERE c.name IS NOT NULL
        ON CONFLICT (name, city, state) DO UPDATE SET
            created_at                       = EXCLUDED.created_at,
            is_presential_clinic             = EXCLUDED.is_presential_clinic,
            is_online_clinic                 = EXCLUDED.is_online_clinic,
            zip_code                         = EXCLUDED.zip_code,
            consult_price                    = EXCLUDED.consult_price,
            duration_minutes                 = EXCLUDED.duration_minutes,
            accepts_insurance_providers      = EXCLUDED.accepts_insurance_providers,
            provides_accessibility_standards = EXCLUDED.provides_accessibility_standards,
            online_clinic_consult_price      = EXCLUDED.online_clinic_consult_price,
            online_clinic_duration_minutes   = EXCLUDED.online_clinic_duration_minutes,
            online_clinic_accepts_insurance_providers = EXCLUDED.online_clinic_accepts_insurance_providers;
    """))

    # -------------------------------------------------------------------------
    # 5) DIM PROFESSIONAL  (chave natural: full_name, state)
    # -------------------------------------------------------------------------
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS lacreisaude_model.dim_lacreisaude_professional
        (
            professional_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at       TIMESTAMP WITHOUT TIME ZONE,
            full_name        VARCHAR,
            profile_status   VARCHAR,
            active           BOOLEAN,
            published        BOOLEAN,
            specialty        VARCHAR,
            ethnic_group     VARCHAR,
            gender_identity  VARCHAR,
            pronoun          VARCHAR,
            sexual_orientation VARCHAR,
            profile_type     VARCHAR,
            disability_type  TEXT[],
            state            VARCHAR
        );
        CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_prof_fullname_state
            ON lacreisaude_model.dim_lacreisaude_professional (full_name, state);
    """))

    conn.execute(text("""
        WITH disab AS (
            SELECT pdt.professional_id,
                ARRAY_REMOVE(ARRAY_AGG(dt.name::text), NULL) AS disab_arr
            FROM lacreisaude_staging_02.lacreisaude_professional_disability_types pdt
            LEFT JOIN lacreisaude_staging_02.lacreiid_disabilitytype dt
            ON pdt.disabilitytype_id = dt.id
            GROUP BY pdt.professional_id
        )
        INSERT INTO lacreisaude_model.dim_lacreisaude_professional
        (
            created_at, full_name, profile_status, active, published, specialty,
            ethnic_group, gender_identity, pronoun, sexual_orientation, profile_type,
            disability_type, state
        )
        SELECT DISTINCT
            p.created_at, p.full_name, p.profile_status, p.active, p.published, p.specialty,
            COALESCE(eg.name::text, p.ethnic_group::text) AS ethnic_group,
            COALESCE(gi.name::text, p.gender_identity::text) AS gender_identity,
            COALESCE(prn.pronoun::text, p.pronoun::text) AS pronoun,
            COALESCE(so.name::text, p.sexual_orientation::text) AS sexual_orientation,
            COALESCE(pd.profile_type::text, p.privacy_document_id::text) AS profile_type,
            COALESCE(d.disab_arr, ARRAY[]::text[]) AS disability_type,
            COALESCE(s_prof.name, p.state_id::text) AS state
        FROM lacreisaude_staging_02.lacreisaude_professional p
        LEFT JOIN disab d ON d.professional_id = p.professional_id::varchar
        LEFT JOIN lacreisaude_staging_02.lacreiid_ethnicgroup eg ON eg.id = p.ethnic_group
        LEFT JOIN lacreisaude_staging_02.lacreiid_genderidentity gi ON gi.id = p.gender_identity
        LEFT JOIN lacreisaude_staging_02.lacreiid_pronoun prn ON prn.id = p.pronoun
        LEFT JOIN lacreisaude_staging_02.lacreiid_sexualorientation so ON so.id = p.sexual_orientation
        LEFT JOIN lacreisaude_staging_02.lacrei_privacydocument pd ON pd.id = p.privacy_document_id
        LEFT JOIN lacreisaude_staging_02.address_state s_prof ON s_prof.id = p.state_id
        WHERE p.full_name IS NOT NULL
        ON CONFLICT (full_name, state) DO UPDATE SET
            created_at        = EXCLUDED.created_at,
            profile_status    = EXCLUDED.profile_status,
            active            = EXCLUDED.active,
            published         = EXCLUDED.published,
            specialty         = EXCLUDED.specialty,
            ethnic_group      = EXCLUDED.ethnic_group,
            gender_identity   = EXCLUDED.gender_identity,
            pronoun           = EXCLUDED.pronoun,
            sexual_orientation= EXCLUDED.sexual_orientation,
            disability_type   = EXCLUDED.disability_type;
    """))

    # -------------------------------------------------------------------------
    # 6) DIM PATIENT  (chave natural: patient_key (hash de first_name, last_name, birth_date))
    # -------------------------------------------------------------------------
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS lacreisaude_model.dim_lacreisaude_patient
        (
            patient_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            patient_key     VARCHAR,
            created_at      TIMESTAMP WITHOUT TIME ZONE,
            first_name      VARCHAR,
            last_name       VARCHAR,
            birth_date      TIMESTAMP WITHOUT TIME ZONE,
            is_active       BOOLEAN,
            profile_type    VARCHAR,
            ethnic_group    VARCHAR,
            gender_identity VARCHAR,
            pronoun         VARCHAR,
            sexual_orientation VARCHAR,
            disability_type TEXT[]
        );
        CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_patient_key
    ON lacreisaude_model.dim_lacreisaude_patient (patient_key);
    """))

    conn.execute(text("""
        WITH prof_disab AS (
         SELECT pdt.profile_id,
             ARRAY_REMOVE(ARRAY_AGG(dt.name::text), NULL) AS disab_arr
         FROM lacreisaude_staging_02.lacreiid_profile_disability_types pdt
         LEFT JOIN lacreisaude_staging_02.lacreiid_disabilitytype dt
           ON pdt.disabilitytype_id = dt.id
         GROUP BY pdt.profile_id
        ),
        base AS (
            SELECT
                u.created_at AS created_at,
                u.first_name,
                u.last_name,
                u.birth_date,
                u.is_active,
                pd.profile_type,
                COALESCE(eg_pr.name::text, pr.ethnic_group::text)        AS ethnic_group,
                COALESCE(gi_pr.name::text, pr.gender_identity::text)     AS gender_identity,
                COALESCE(prn_pr.pronoun::text, pr.pronoun::text)         AS pronoun,
                COALESCE(so_pr.name::text, pr.sexual_orientation::text)  AS sexual_orientation,
                COALESCE(d.disab_arr, ARRAY[]::text[]) AS disability_type
            FROM lacreisaude_staging_02.lacreiid_user u
            LEFT JOIN lacreisaude_staging_02.lacreiid_profile pr
                   ON pr.user_id = u.user_id
            LEFT JOIN prof_disab d
                   ON d.profile_id = pr.profile_id
            LEFT JOIN lacreisaude_staging_02.lacrei_privacydocument pd
             ON pd.id = u.privacy_document_id
         LEFT JOIN lacreisaude_staging_02.lacreiid_ethnicgroup eg_pr ON eg_pr.id = pr.ethnic_group
         LEFT JOIN lacreisaude_staging_02.lacreiid_genderidentity gi_pr ON gi_pr.id = pr.gender_identity
         LEFT JOIN lacreisaude_staging_02.lacreiid_pronoun prn_pr ON prn_pr.id = pr.pronoun
         LEFT JOIN lacreisaude_staging_02.lacreiid_sexualorientation so_pr ON so_pr.id = pr.sexual_orientation
         WHERE pd.profile_type = 'Paciente'  -- Considerar apenas profiles do tipo Paciente (alterar para o tipo correto se necessário)
        )
        INSERT INTO lacreisaude_model.dim_lacreisaude_patient
        (
            patient_key, created_at, first_name, last_name, birth_date, is_active, profile_type,
            ethnic_group, gender_identity, pronoun, sexual_orientation, disability_type
        )
        SELECT DISTINCT
            md5(lower(coalesce(first_name,'') || '|' || coalesce(last_name,'') || '|' || coalesce(birth_date::text,''))) AS patient_key,
            created_at, first_name, last_name, birth_date, is_active, profile_type,
            ethnic_group, gender_identity, pronoun, sexual_orientation, disability_type
        FROM base
        WHERE first_name IS NOT NULL OR last_name IS NOT NULL OR birth_date IS NOT NULL
        ON CONFLICT (patient_key) DO UPDATE SET
            created_at       = EXCLUDED.created_at,
            is_active        = EXCLUDED.is_active,
            profile_type     = EXCLUDED.profile_type,
            ethnic_group     = EXCLUDED.ethnic_group,
            gender_identity  = EXCLUDED.gender_identity,
            pronoun          = EXCLUDED.pronoun,
            sexual_orientation = EXCLUDED.sexual_orientation,
            disability_type  = EXCLUDED.disability_type;
    """))

    # -------------------------------------------------------------------------
    # 7) FACT APPOINTMENTS
    # -------------------------------------------------------------------------
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS lacreisaude_model.fact_lacreisaude_appointments
        (
            id_fact_appointment INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            appointment_fingerprint VARCHAR,
            created_date_id     INTEGER REFERENCES lacreisaude_model.dim_lacreisaude_date(date_id),
            status              VARCHAR,
            type                VARCHAR,
            date_id             INTEGER NOT NULL REFERENCES lacreisaude_model.dim_lacreisaude_date(date_id),
            waiting_time        NUMERIC,
            professional_id     INTEGER REFERENCES lacreisaude_model.dim_lacreisaude_professional(professional_id),
            patient_id          INTEGER REFERENCES lacreisaude_model.dim_lacreisaude_patient(patient_id),
            clinic_id           INTEGER REFERENCES lacreisaude_model.dim_lacreisaude_clinic(clinic_id),
            report_id           INTEGER REFERENCES lacreisaude_model.dim_lacreisaude_report(report_id),
            -- Denormalized cancellation attributes (no source ids stored in dims)
            cancellation_created_at TIMESTAMP WITHOUT TIME ZONE,
            cancellation_reason     VARCHAR
        );
        CREATE INDEX IF NOT EXISTS idx_fact_date_id          ON lacreisaude_model.fact_lacreisaude_appointments(date_id);
        CREATE INDEX IF NOT EXISTS idx_fact_created_date_id  ON lacreisaude_model.fact_lacreisaude_appointments(created_date_id);
        CREATE INDEX IF NOT EXISTS idx_fact_professional_id  ON lacreisaude_model.fact_lacreisaude_appointments(professional_id);
        CREATE INDEX IF NOT EXISTS idx_fact_patient_id       ON lacreisaude_model.fact_lacreisaude_appointments(patient_id);
        CREATE INDEX IF NOT EXISTS idx_fact_report_id        ON lacreisaude_model.fact_lacreisaude_appointments(report_id);
        CREATE INDEX IF NOT EXISTS idx_fact_cancellation_created_at ON lacreisaude_model.fact_lacreisaude_appointments(cancellation_created_at);
        CREATE INDEX IF NOT EXISTS idx_fact_clinic_id        ON lacreisaude_model.fact_lacreisaude_appointments(clinic_id);
        CREATE UNIQUE INDEX IF NOT EXISTS ux_fact_appointment_fingerprint
            ON lacreisaude_model.fact_lacreisaude_appointments (appointment_fingerprint);
    """))

    conn.execute(text("""
        WITH ap AS (
            SELECT
                a.id,
                a.status,
                a.type,
                a.appointment_date,
                a.created_at,
                a.appointment_date::date  AS appt_d,
                a.created_at::date        AS created_d,
                a.professional_id,
                a.user_id
            FROM lacreisaude_staging_02.lacreiid_appointment a
        ),
        d_appt AS (
            SELECT d.calendar_date, d.date_id
            FROM lacreisaude_model.dim_lacreisaude_date d
        ),
        d_created AS (
            SELECT d.calendar_date, d.date_id
            FROM lacreisaude_model.dim_lacreisaude_date d
        ),
        prof_src AS (
            SELECT p.professional_id::varchar AS src_prof_id,
                   p.full_name,
                   COALESCE(s.name, p.state_id::text) AS state
            FROM lacreisaude_staging_02.lacreisaude_professional p
            LEFT JOIN lacreisaude_staging_02.address_state s ON s.id = p.state_id
        ),
        d_prof AS (
            SELECT dp.professional_id, dp.full_name, dp.state
            FROM lacreisaude_model.dim_lacreisaude_professional dp
        ),
        user_src AS (
            -- Busca os atributos naturais do paciente a partir do user_id do appointment
            SELECT u.user_id, u.first_name, u.last_name, u.birth_date
            FROM lacreisaude_staging_02.lacreiid_user u
        ),
        d_pat AS (
            -- Dimensão patient (chave substituta)
            SELECT dp.patient_id, dp.first_name, dp.last_name, dp.birth_date
            FROM lacreisaude_model.dim_lacreisaude_patient dp
        ),
        rep_src AS (
            SELECT r.appointment_id, r.created_at, r.feedback, r.eval
            FROM lacreisaude_staging_02.lacreiid_report r
        ),
        d_rep AS (
            SELECT dr.report_id, dr.created_at, dr.feedback, dr.evaluation
            FROM lacreisaude_model.dim_lacreisaude_report dr
        ),
        -- Normalize and deduplicate cancellations by appointment_id so we can
        -- map cancellations to appointments deterministically without a separate
        -- mapping table. We pick the most recent cancellation per appointment.
        canc_src AS (
            SELECT appointment_id, created_at, reason FROM (
                SELECT
                    NULLIF(TRIM(appointment_id), '')::varchar AS appointment_id,
                    CASE WHEN created_at IS NULL THEN NULL
                         ELSE date_trunc('second', created_at::timestamptz AT TIME ZONE 'UTC')
                    END AS created_at,
                    NULLIF(TRIM(reason), '')::varchar AS reason,
                    ROW_NUMBER() OVER (
                        PARTITION BY NULLIF(TRIM(appointment_id), '')
                        ORDER BY (CASE WHEN created_at IS NULL THEN to_timestamp(0) ELSE created_at END) DESC
                    ) AS rn
                FROM lacreisaude_staging_02.lacreiid_cancellation
            ) t
            WHERE rn = 1
        ),
        -- We denormalize cancellation into the fact; no need to load dim_cancellation here
        joined AS (
            SELECT
                ap.id AS src_appointment_id,
                ap.status, ap.type,

                dap.date_id    AS date_id,
                dcr.date_id    AS created_date_id,

                -- WAITING TIME (em minutos)
                CASE 
                    WHEN ap.appointment_date IS NOT NULL AND ap.created_at IS NOT NULL 
                    THEN FLOOR(EXTRACT(EPOCH FROM (ap.appointment_date - ap.created_at)) / 60.0)::int
                    ELSE NULL
                END AS waiting_time,

                -- PROFESSIONAL
                dp.professional_id AS professional_id,

                -- PATIENT
                dpa.patient_id AS patient_id,

                -- REPORT
                dr.report_id   AS report_id,

                -- CLINIC (via professional)
                dc.clinic_id   AS clinic_id,

                -- CANCELLATION (denormalized into fact)
                cs.created_at AS cancellation_created_at,
                cs.reason     AS cancellation_reason

            FROM ap
            LEFT JOIN d_appt   dap ON dap.calendar_date = ap.appt_d
            LEFT JOIN d_created dcr ON dcr.calendar_date = ap.created_d

            -- Compare professional IDs as text to avoid casting errors when source ids are non-numeric
            LEFT JOIN prof_src ps  ON ps.src_prof_id = ap.professional_id::varchar
            LEFT JOIN d_prof   dp  ON dp.full_name = ps.full_name AND dp.state = ps.state

            -- Join para buscar a clínica associada ao profissional
            LEFT JOIN lacreisaude_staging_02.lacreisaude_clinic sc 
                ON CAST(sc.professional_id AS VARCHAR) = ap.professional_id::varchar
            LEFT JOIN lacreisaude_staging_02.address_state stg_state ON stg_state.id = sc.state_id
            LEFT JOIN lacreisaude_model.dim_lacreisaude_clinic dc 
                ON dc.name = sc.name 
                AND dc.city = sc.city 
                AND dc.state = stg_state.name

          -- Busca o paciente a partir do user_id do appointment
          LEFT JOIN user_src us  ON us.user_id = ap.user_id::varchar
          LEFT JOIN d_pat   dpa  ON dpa.first_name = us.first_name
                            AND dpa.last_name  = us.last_name
                            AND ((dpa.birth_date IS NULL AND us.birth_date IS NULL)
                                OR dpa.birth_date = us.birth_date)

            LEFT JOIN rep_src rs   ON rs.appointment_id = ap.id
            LEFT JOIN d_rep   dr   ON dr.created_at = rs.created_at
                                   AND COALESCE(dr.feedback, '') = COALESCE(rs.feedback, '')
                                   AND COALESCE(dr.evaluation, -2147483648) = COALESCE(rs.eval, -2147483648)

            LEFT JOIN canc_src cs  ON cs.appointment_id = ap.id::varchar
        )
        -- Compute a deterministic fingerprint for each appointment (hashed source id)
        -- We store only the hash to avoid keeping source IDs in the model
        INSERT INTO lacreisaude_model.fact_lacreisaude_appointments
        (
            appointment_fingerprint, created_date_id, status, type, date_id, waiting_time,
            professional_id, patient_id, clinic_id, report_id,
            cancellation_created_at, cancellation_reason
        )
        SELECT DISTINCT
            md5(COALESCE(j.src_appointment_id::text, '') || '|' || COALESCE(j.date_id::text, '')) AS appointment_fingerprint,
            j.created_date_id, j.status, j.type, j.date_id, j.waiting_time,
            j.professional_id, j.patient_id, j.clinic_id, j.report_id,
            j.cancellation_created_at, j.cancellation_reason
        FROM (
            SELECT 
                ap.src_appointment_id AS src_appointment_id,
                created_date_id, status, type, date_id, waiting_time, professional_id, patient_id, clinic_id, report_id,
                cancellation_created_at, cancellation_reason,
                -- Anonimiza os campos sensíveis após o join
                NULL AS first_name, NULL AS last_name
            FROM joined ap
        ) j
        ON CONFLICT (appointment_fingerprint) DO UPDATE SET
            created_date_id = EXCLUDED.created_date_id,
            status = EXCLUDED.status,
            type = EXCLUDED.type,
            date_id = EXCLUDED.date_id,
            waiting_time = EXCLUDED.waiting_time,
            professional_id = EXCLUDED.professional_id,
            patient_id = EXCLUDED.patient_id,
            clinic_id = EXCLUDED.clinic_id,
            report_id = EXCLUDED.report_id,
            cancellation_created_at = EXCLUDED.cancellation_created_at,
            cancellation_reason = EXCLUDED.cancellation_reason;
    """))

    # Anonimiza os campos first_name e last_name após uso nos joins (adicionar outros campos sensíveis de outras tabelas se necessário)
    conn.execute(text("""
        UPDATE lacreisaude_model.dim_lacreisaude_patient
        SET first_name = NULL, last_name = NULL;
    """))
    return {"ok": True, "msg": "ETL do modelo concluído (dimensões e fato atualizados e nomes anonimizados)."}